substitutions:
  _GCS_CACHE_BUCKET: ceres-cache
  _CERES_PROJECT: ceres-query-service
  _CERES_APP: query-service
  _APP_NAMESPACE: default
  _CLOUDSDK_COMPUTE_ZONE: us-east1-b
  _CLOUDSDK_CONTAINER_CLUSTER: ceres

steps:
  # Load the cached files from GCS if they exist.
  - id: PULL_DOWN_CACHE
    waitFor: ['-']
    name: gcr.io/cloud-builders/gsutil
    dir: /root
    entrypoint: bash
    args:
    - -c
    - |
      (
        gsutil cp gs://${_GCS_CACHE_BUCKET}/${_CERES_PROJECT}-m2-cache.tar.gz /tmp/m2-cache.tar.gz &&
        tar -xzf /tmp/m2-cache.tar.gz
      ) || echo 'Cache not found'
    volumes:
    - name: user.home
      path: /root

  - id: COMPILE_AND_PUSH_CONTAINER
    name: 'maven:3.6-jdk-11'
    env:
    - 'SHORT_SHA=$SHORT_SHA'
    - 'BRANCH_NAME=$BRANCH_NAME'
    args:
    - mvn
    - compile
    - jib:build
    - "-B"
    - "-Dmaven.test.skip=true"
    - "-Ddocker.image.prefix=gcr.io/$PROJECT_ID"
    volumes:
    - name: user.home
      path: /root

  # Saves the files to the GCS cache.
  - id: PUSH_UP_CACHE
    waitFor:
    - COMPILE_AND_PUSH_CONTAINER
    name: gcr.io/cloud-builders/gsutil
    dir: /root
    entrypoint: bash
    # Caches the local Maven repository.
    args:
    - -c
    - |
      set -ex
      tar -czf /tmp/m2-cache.tar.gz .m2 &&
      gsutil cp /tmp/m2-cache.tar.gz gs://${_GCS_CACHE_BUCKET}/${_CERES_PROJECT}-m2-cache.tar.gz
    volumes:
    - name: user.home
      path: /root

  - id: HELM_CLONE
    name: 'gcr.io/cloud-builders/git'
    waitFor:
      - COMPILE_AND_PUSH_CONTAINER
      - PUSH_UP_CACHE
    args: ['clone', 'https://source.developers.google.com/p/$PROJECT_ID/r/github_rackspace-segment-support_helm-ceres-${_CERES_APP}', '/workspace/helm-ceres-${_CERES_APP}']

  # set _CLOUDSDK_COMPUTE_REGION in the build trigger for non-dev clusters
  - id: DEPLOY_APPLICATION
    name: 'gcr.io/$PROJECT_ID/helm'
    args: ['upgrade', '--install', '${_CERES_APP}', '--namespace', '${_APP_NAMESPACE}', '/workspace/helm-ceres-${_CERES_APP}']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_COMPUTE_REGION=${_CLOUDSDK_COMPUTE_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'TILLERLESS=true'

options:
  substitution_option: 'ALLOW_LOOSE'
