substitutions:
  _GCS_CACHE_BUCKET: ceres-cache
  _CERES_PROJECT: ceres-query-service

steps:

    # This is ugly because of
    # https://github.com/GoogleContainerTools/jib/issues/1500#issuecomment-466207421
  - id: FIX_DOCKER
    name: gcr.io/cloud-builders/gsutil
    waitFor: ['-']
    dir: /root
    entrypoint: bash
    args:
    - -c
    - # Links the Docker config to /root/.docker/config.json so that Jib picks it up.
      # Note that this is only a temporary workaround.
      # See https://github.com/GoogleContainerTools/jib/pull/1479.
      |
      mkdir .docker &&
      ln -vs $$HOME/.docker/config.json .docker/config.json
    volumes:
    - name: user.home
      path: /root

  # Load the cached files from GCS if they exist.
  - id: PULL_DOWN_CACHE
    waitFor: ['-']
    name: gcr.io/cloud-builders/gsutil
    dir: /root
    entrypoint: bash
    args:
    - -c
    - |
      (
        gsutil cp gs://${_GCS_CACHE_BUCKET}/${_CERES_PROJECT}-m2-cache.tar.gz /tmp/m2-cache.tar.gz &&
        tar -xzf /tmp/m2-cache.tar.gz
      ) || echo 'Cache not found'
    volumes:
    - name: user.home
      path: /root

  - id: COMPILE_AND_PUSH_CONTAINER
    name: 'maven:3.6-jdk-8'
    env:
    - 'SHORT_SHA=$SHORT_SHA'
    - 'BRANCH_NAME=$BRANCH_NAME'
    args:
    - mvn
    - -B
    - compile
    - jib:build
    - "-Dmaven.test.skip=true"
    - "-Ddocker.image.prefix=gcr.io/$PROJECT_ID"
    volumes:
    - name: user.home
      path: /root

  # Saves the files to the GCS cache.
  - id: PUSH_UP_CACHE
    waitFor:
    - COMPILE_AND_PUSH_CONTAINER
    name: gcr.io/cloud-builders/gsutil
    dir: /root
    entrypoint: bash
    # Caches the local Maven repository.
    args:
    - -c
    - |
      set -ex
      tar -czf /tmp/m2-cache.tar.gz .m2 &&
      gsutil cp /tmp/m2-cache.tar.gz gs://${_GCS_CACHE_BUCKET}/${_CERES_PROJECT}-m2-cache.tar.gz
    volumes:
    - name: user.home
      path: /root

